blog/urls.py
from django.urls import path
from . import views

app_name='blog'

urlpatterns=[
    path('', views.post_list, name='post_list'),
    path('<int:pk>/', views.post_detail, name='post_detail'),
    path('new/', views.post_new,name='post_new'),
]

users/urls.py
from django.urls import path

urlpatterns=[

]

uuid_user2/urls.py
from django.contrib import admin
from django.urls import path,include
from django.shortcuts import redirect

#media 파일서빙
#media폴더에 파일을 불러올때 사용
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls')),
    path('', lambda request:redirect('blog:post_list'), name='root'),
    path('users/', include('users.urls')),
]+ static(settings.MEDIA_URL ,document_root=settings.MEDIA_ROOT) #파일서빙

blog/models.py
from django.db import models
from django.urls import reverse
# Create your models here.

from django import forms

#썸네일 패키지
from imagekit.models import ImageSpecField,ProcessedImageField
from imagekit.processors import ResizeToFill,Thumbnail,SmartResize,Resize

#제목 글자 검사
#model에 validators 를 정의하는 것을 권장
def min_length_2_validator(value):
    if len(value) <2:
        raise forms.ValidationError('2글자 이상 입력')


class Post(models.Model):
    title = models.CharField(max_length=200, validators=[min_length_2_validator])
    content = models.TextField(blank=True,null=True)
    #photo = models.ImageField(blank=True,null=True,upload_to='post_photo')
    created_at = models.DateTimeField(auto_now_add=True, null=True)
    updated_at = models.DateTimeField(auto_now=True, null=True)

    #썸네일
    # photo_thumbnail = ImageSpecField(
    #     source='photo',
    #     processors=[Resize(300,200)],
    #     format='PNG',
    #     options={'quality': 60}
    # )
    #media폴더, 지정된 폴더 이미지 불러오기
    photo = ProcessedImageField(
        blank=True,
        null=True,
        upload_to='post_photo',
        processors=[Resize(500,500)],
        format='PNG',
        options={'quality':60},
    )

    def __str__(self):
        return self.title

    def get_absolute_url(self): #redirect시 활용
        return reverse('blog:post_detail', args=[self.id])

users/models.py
# Create your models here.
from django.db import models
from django.contrib.auth.models import PermissionsMixin, AbstractUser
#from django.contrib.auth.base_user import AbstractBaseUser
from django.utils.translation import ugettext_lazy as _
from django.utils import timezone
from django.contrib.auth.models import UserManager as AuthUserManager
import uuid
# Create your models here.

from django.conf import settings

class UserManager(AuthUserManager):
    use_in_migrations=True
    def _create_user(self,email,password, **extra_fields):
        if not email:
            raise ValueError('이메일 입력 오류')
        email = self.normalize_email(email)
        user =self.model(email=email , **extra_fields)
        user.set_password(password)
        user.save(using=self.db)
        return user

    def create_user(self,email,password=None, **extra_fields):
        extra_fields.setdefault('is_staff',False)     #스태프권한
        extra_fields.setdefault('is_superuser',False) #슈퍼유저권환
        return super()._create_user(email,password, **extra_fields)

    def create_superuser(self,email,password,**extra_fields):
        extra_fields.setdefault('is_staff',True)
        extra_fields.setdefault('is_superuser',True)

        if extra_fields.get('is_staff') is not True:
            raise ValueError('슈퍼유저는 staff권한을 가져야합니다')
        if extra_fields.get('is_superuser') is not True:
            raise ValueError('슈퍼유저는 슈퍼유저권한을 가져야합니다')
        return super()._create_user(email,password, **extra_fields)


class User(AbstractUser):
    uuid = models.UUIDField(default=uuid.uuid4, primary_key=True,editable=False)
    email = models.EmailField(_('email address'),unique=True)
    nick_name = models.CharField(_('nick_name'),max_length=150,blank=True)
    username= models.CharField(max_length=40,unique=False,default='')

    is_staff= models.BooleanField(
        _('staff_status'),
        default=False,
        help_text=_('사용자가 이 관리 사이트에 로그인 할 수 있는지 여부를 지정합니다.'
        ),
    )
    is_active = models.BooleanField(
        _('active'),
        default=True,
        help_text=_('이 사용자를 활성 상태로 처리해야하는지 여부를 지정합니다'
        '계정을 삭제하는 대신이 항목을 선택 해제하십시오'
        ),
    )

    object=UserManager()
    EMAIL_FIELD = 'email'
    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

    def get_full_name(self):
        full_name= '%s'%(self.nick_name)
        return full_name.strip() #strip :공백 지우기

    def get_short_name(self):
        return self.nick_name


#프로필 생성
class Profile(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL ,on_delete=models.CASCADE)
    profile_website_url= models.URLField(blank=True , null=True)
    profile_blog = models.URLField(blank=True , null=True)
    profile_birthday = models.DateField(blank=True, null=True)

    profile_image = models.ImageField(blank=True, upload_to='user_image', null=True)
    #profile_image = models.ImageField(blank=True, upload_to='user_image/%Y/%m/%d')

blog/forms.py
from django import forms
from .models import Post


#Form 과 Model Form 차이점
#Form 직접 필드 정의 위젯 설정이 필요
#model Form 모델과 필드를 지정하면 모델폼이 자동으로 폼 필드를 생성


# class PostForm(forms.ModelForm):
#     class Meta:
#         model = Post
#         fields = '__all__'


def min_length_3_validator(value):
    if len(value) <3:
        raise forms.ValidationError('3글자이상 입력해주세요')


class PostForm(forms.Form):
    title=forms.CharField(label="제목")
    #title=forms.CharField(validators=[min_length_3_validator])
    content = forms.CharField(widget=forms.Textarea,label="내용")
    photo = forms.ImageField()

    #ModelForm.save 인터페이스를 흉내내어 구현
    #ModelForm이 아니면 save구현해야함
    def save(self, commit=True):
        post = Post(**self.cleaned_data)
        if commit:
            post.save()
        return post

blog/views.py
from django.shortcuts import render
from .models import Post
from .forms import PostForm
from django.shortcuts import redirect ,get_object_or_404
# Create your views here.

def post_list(request):
    qs = Post.objects.all()
    return render(request , 'blog/post_list.html',{
        'post_list':qs
    })
def post_detail(request, pk):
    post =get_object_or_404(Post,pk=pk)
    return render(request, 'blog/post_detail.html',
                  {'post':post,})


def post_new(request ,post=None):
    if request.method =='POST':
        form = PostForm(request.POST,request.FILES)
        if form.is_valid():
            post = form.save()
            return redirect(post)
    else:
        form = PostForm()
        return render(request, 'blog/post_new.html' ,{
            'form':form,
        })

users/views.py
from django.shortcuts import render

# Create your views here.

blog/templates/blog/layout.html
{% extends 'layout.html' %}

blog/templates/blog/post_detail.html
{% extends 'blog/layout.html' %}


{% block content %}

    <h1>{{ post.title }}</h1>
    {{ post.content }}
    {% if post.photo %}
        <img src="{{ post.photo.url }}"  >
    {% else %}

    {% endif %}
    {{ post.created_at }}


    <a href="{% url "blog:post_list" %}">목록</a>
{% endblock %}

blog/templates/blog/post_list.html
{% extends 'blog/layout.html' %}
{% load imagekit %}


{% block content %}
    {% for post in post_list %}

        <a href="{{ post.get_absolute_url }}">
            {{ post.title }}</a>
        <p>{{ post.content }}</p>
        {% if post.photo %}
            <div class="thumbnail">
                <a href="{{ post.get_absolute_url }}">
                    <img src="{{ post.photo.url }}" alt="" width=100px; height=100px;>
                </a>
            </div>
        {% else %}
            <img src="/media/post_photo/businessman.png" width=100px; height=100px;>
        {% endif %}
        <br>
    {% endfor %}

    <a href="{% url "blog:post_new" %}">생성</a>
{% endblock %}

blog/templates/blog/post_new.html
{% extends 'blog/layout.html' %}

{% block content %}
<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="저장하기">
</form>
{% endblock %}

uuid_user2/templates/layout.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>blog</title>
    {% block extra_head %}
    <link rel="stylesheet" href="{% static "main.css" %}"/>
    {% endblock %}
</head>
<body>
    <h1>블로그</h1>
    {% block content %}
    {% endblock %}
    {% block extra_body %}
        <script src="{% static "main.js" %}"></script>
    {% endblock %}
</body>
</html>